name: gemt_bot
description: AI chat bot for Telegram.
version: 1.0.1 

environment:
  sdk: ^3.7.2

dependencies:
  dotenv: ^4.2.0
  http: ^1.3.0
  teledart: ^0.6.1 

dev_dependencies:
  lints: ^5.0.0
